### ISSUE TITLE
issue with this plugin

### ISSUE THREAD

**Issue by sirius2013** [agamemnus/cordova-plugin-xapkreader#43] opened 2016-03-17 05:35 UTC
Hi,
I am very interesting this plugin.
I want to donate if you can help very small thing.

Are you available now?

**Comment by agamemnus** [comment] 2016-03-17 08:59
Let me know what the issue is. I need to update it anyway...

**Comment by sirius2013** [comment] 2016-03-17 09:12
It seems this doesn't support for sdk-23. android 6.0.

**Comment by sirius2013** [comment] 2016-03-17 09:14
and I followed this
https://github.com/agamemnus/cordova-plugin-xapkreader/blob/cordova-5.3.1/test-project-instructions-and-test-obb/instructions.txt

but image didn't show on my app.

**Comment by sirius2013** [comment] 2016-03-17 09:37
and please make sure how did you create obb file.
main.1.com.myproject.obb

**Comment by agamemnus** [comment] 2017-03-07 14:52
Works in 6.5.0 now. I think. Closing.

**Closed by agamemnus** 2017-03-07 14:52 UTC
