### ISSUE TITLE
Build failure when using cordova-plugin-xapkreader

### ISSUE THREAD

**Issue by satchmo7** [agamemnus/cordova-plugin-xapkreader#19] opened 2015-05-13 16:34 UTC
Hi,

I receive the following error when trying to build my app via the terminal.

What went wrong:
```
Execution failed for task ':..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play_apk_expansion:downloader_library:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
```
Can you please help?

**Comment by agamemnus** [comment] 2015-05-13 16:47
Well, what's the compiler error output?

Are you using Cordova 5? There are some problems with using it and this plugin at the moment, although I haven't seen that particular error yet.

**Comment by ashNorton** [comment] 2015-05-14 08:13
Hi,

Please find full failure output below:

/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:26: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.AESObfuscator;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:27: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.APKExpansionPolicy;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:28: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseChecker;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:29: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseCheckerCallback;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:30: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.Policy;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:756: error:
cannot find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                  ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:756: error:
cannot find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                                               ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:757: error:
cannot find symbol
                    new AESObfuscator(getSALT(), mContext.getPackageName(),
deviceId));
                        ^
  symbol:   class AESObfuscator
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:765: error:
cannot find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                  ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:765: error:
cannot find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                                               ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:768: error:
cannot find symbol
            checker.checkAccess(new LicenseCheckerCallback() {
                                    ^
  symbol:   class LicenseCheckerCallback
  location: class DownloaderService.LVLRunnable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:pla
y_apk_expansion:downloader_library:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

Total time: 4.942 secs

/Users/ashleynorton/fuji_android/platforms/android/cordova/node_modules/q/q.
js:126
                    throw e;
                          ^
Error code 1 for command:
/Users/ashleynorton/fuji_android/platforms/android/gradlew with args:
cdvBuildDebug,-b,/Users/ashleynorton/fuji_android/platforms/android/build.gr
adle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error:
/Users/ashleynorton/fuji_android/platforms/android/cordova/build: Command
failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/ashleynorton/fuji_android/platforms/android/cordova/build:
Command failed with exit code 1
    at ChildProcess.whenDone
(/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/su
perspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I just ran cordova platform version android and it tells me I¹m running
Installed platforms: android 4.0.0
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios

Thank you for your help in advance.



On 13/05/2015 17:47, "agamemnus" <notifications@github.com> wrote:

> Well, what's the compiler error output?
> 
> Are you using Cordova 5? There are some problems with using it and this plugin
> at the moment, although I haven't seen that particular error yet.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -101742660> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by ashNorton** [comment] 2015-05-14 08:18
Sorry you asked what version of Cordova I am running, it¹s 5.0.0.


On 13/05/2015 17:47, "agamemnus" <notifications@github.com> wrote:

> Well, what's the compiler error output?
> 
> Are you using Cordova 5? There are some problems with using it and this plugin
> at the moment, although I haven't seen that particular error yet.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -101742660> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by agamemnus** [comment] 2015-05-14 08:19
Okay, so I think you're using Cordova 5 which changed some things around. I
don't have a fix for this yet. I'll try this weekend. Meanwhile, if you
want, you can downgrade by adding the specific version in your cordova
install command line command.

**Comment by ashNorton** [comment] 2015-05-14 08:54
Thank you for your help so far, I have successfully reverted back to Cordova
3.4.1-0.1.0, but I receive the following when trying to build.

ANDROID_HOME=/Users/ashleynorton/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
Running: /Users/ashleynorton/fuji_android/platforms/android/gradlew
cdvBuildDebug -b 
/Users/ashleynorton/fuji_android/platforms/android/build.gradle
-Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileLint
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:copyDebugLint
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:mergeDebugProguardFiles
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:preBuild
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:preDebugBuild
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:checkDebugManifest
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:preDebugTestBuild
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:prepareAndroidCordovaLibUnspecifiedDebugLi
brary                                                UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:prepareDebugDependencies
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileDebugAidl
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileDebugRenderscript
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:generateDebugBuildConfig
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:generateDebugAssets
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:mergeDebugAssets
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:generateDebugResValues
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:generateDebugResources
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:mergeDebugResources
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:processDebugManifest
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:processDebugResources
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:generateDebugSources
UP-TO-DATE
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileDebugJava
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:26: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.AESObfuscator;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:27: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.APKExpansionPolicy;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:28: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseChecker;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:29: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseCheckerCallback;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:30: error:
package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.Policy;
                                           ^
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:756: error:
cannot find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                  ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:756: error:
cannot find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                                               ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:757: error:
cannot find symbol
                    new AESObfuscator(getSALT(), mContext.getPackageName(),
deviceId));
                        ^
  symbol:   class AESObfuscator
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:765: error:
cannot find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                  ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:765: error:
cannot find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                                               ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
/Users/ashleynorton/fuji_android/plugins/com.flyingsoftgames.xapkreader/andr
oid-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/a
ndroid/vending/expansion/downloader/impl/DownloaderService.java:768: error:
cannot find symbol
            checker.checkAccess(new LicenseCheckerCallback() {
                                    ^
  symbol:   class LicenseCheckerCallback
  location: class DownloaderService.LVLRunnable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play
_apk_expansion:downloader_library:compileDebugJava
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:pla
y_apk_expansion:downloader_library:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

Total time: 18.491 secs

/Users/ashleynorton/fuji_android/platforms/android/cordova/node_modules/q/q.
js:126
                    throw e;
                          ^
Error code 1 for command:
/Users/ashleynorton/fuji_android/platforms/android/gradlew with args:
cdvBuildDebug,-b,/Users/ashleynorton/fuji_android/platforms/android/build.gr
adle,-Dorg.gradle.daemon=true
Error: /Users/ashleynorton/fuji_android/platforms/android/cordova/build:
Command failed with exit code 1
    at ChildProcess.whenDone
(/usr/local/lib/node_modules/cordova/src/superspawn.js:126:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

Appreciate your help.

Cheers,
Ash

On 14/05/2015 09:19, "agamemnus" <notifications@github.com> wrote:

> Okay, so I think you're using Cordova 5 which changed some things around. I
> don't have a fix for this yet. I'll try this weekend. Meanwhile, if you
> want, you can downgrade by adding the specific version in your cordova
> install command line command.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -101967311> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by ashNorton** [comment] 2015-05-14 12:46
Hi,

Did you see the latest errors I am receiving? Have you any ideas what I am
doing wrong?

Kind regards


On 14/05/2015 09:19, "agamemnus" <notifications@github.com> wrote:

> Okay, so I think you're using Cordova 5 which changed some things around. I
> don't have a fix for this yet. I'll try this weekend. Meanwhile, if you
> want, you can downgrade by adding the specific version in your cordova
> install command line command.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -101967311> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by agamemnus** [comment] 2015-05-14 23:06
It looks like you didn't fully revert. Make sure the ``platform/android`` is rebuilt as well.

**Comment by FabianMeul** [comment] 2015-05-15 08:54
I'm also having the same compilation errors on OSX 10.10.3 and Cordova 5.0.0

**Comment by satchmo7** [comment] 2015-05-15 14:46
Hi,

It turns out my development environment wasn¹t set up correctly, I have
fixed this and can now build the App, but when I install onto my device and
transfer the .obb to the devices local storage the images still do not link
using content://com.company.app/main_expansion/photos/myfile.png"

Any ideas?


On 15/05/2015 00:06, "agamemnus" <notifications@github.com> wrote:

> It looks like you didn't fully revert. Make sure the platform/android is
> rebuilt as well.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -102195710> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by FabianMeul** [comment] 2015-05-15 14:48
@satchmo7 Could you describe what you changed in your development environment to resolve the issue?

**Comment by satchmo7** [comment] 2015-05-15 15:05
Sure no worries.

1. Download the latest SDK
2. From Android Studio download the necessary packages, so for this plugin
it was Google Play APK Expansion Library and Google Play Licensing Library
3. install Cordova 3.4.1-0.1.0 instead of 5.0.0
4. You should have a file called local.properties within your
<app-directory>\platforms\android folder. If you don't have one then you can
create it. 
5. update your details to point it to your correct android sdk folder. I.e
sdk.dir=/Users/yourname/Library/Android/sdk Note: this file also needs to be
copied into your CordovaLib folder, which is one folder deeper:
<app-directory>\platforms\android\CordovaLib
6. If working locally make sure all folder permissions are set to 777.

Then build again.





On 15/05/2015 15:48, "FabianMeul" <notifications@github.com> wrote:

> @satchmo7 <https://github.com/satchmo7>  Could you describe what you changed
> in your development environment to resolve the issue?
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -102419247> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by satchmo7** [comment] 2015-05-15 16:07
@agamemnus Can I send you my project files for you to take a look at, as I feel i have exhausted all options now.

**Comment by agamemnus** [comment] 2015-05-15 16:24
content://com.company.app/main_expansion/photos/myfile.png -->

content://com.company.app.expansion/photos/myfile.png"

**Comment by agamemnus** [comment] 2015-05-15 16:40
FabianMeul, Cordova 5 is still an issue.

**Comment by satchmo7** [comment] 2015-05-16 10:26
Unfortunately content://com.company.app.expansion/photos/myfile.png didn't work either.


agamemnus <notifications@github.com> , 5/15/2015 5:24 PM:
content://com.company.app/main_expansion/photos/myfile.png -->
 
 content://com.company.app.expansion/photos/myfile.png"

**Comment by satchmo7** [comment] 2015-05-18 09:01
Agamemnus, can you please help me resolve this issue as I need to publish
the App ASAP.


On 15/05/2015 17:40, "agamemnus" <notifications@github.com> wrote:

> FabianMeul, Cordova 5 is still an issue.
> 
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/agamemnus/cordova-plugin-xapkreader/issues/19#issuecomment
> -102455454> .
> 
>  
>    
>  
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by agamemnus** [comment] 2015-05-18 12:15
Sorry I didn't have time to work on this on the weekend. Have you tried
going thorough the test project steps?

**Comment by satchmo7** [comment] 2015-05-18 12:29
No worries, I followed the steps posted here with no joy https://iphonedevlog.wordpress.com/2014/12/12/adding-an-android-apk-expansion-file-to-a-cordova-project/

**Comment by agamemnus** [comment] 2015-05-18 14:53
There's something wrong with your directory structure. There are test
project instructions in my project directory that are more barebones. Try
to follow that instead.

**Comment by satchmo7** [comment] 2015-05-18 14:55
All working now, thank you for your help.

**Comment by FabianMeul** [comment] 2015-05-18 14:56
Any update on when this plugin will be cordova-5.0.0 compatible? :-)

**Comment by agamemnus** [comment] 2015-05-18 16:44
I will try for next weekend. It would help if someone figured out if it's
possible to link files like I've been doing, in 5. What are the
modifications needed, is it a bug in 5, etc.

**Comment by shuklaalok7** [comment] 2015-06-06 18:43
I think #18 and this issue both are similar. Both of these talk about the plugin not working (not compatible) with Cordova 5.0.0.

**Comment by agamemnus** [comment] 2015-06-06 21:05
Please post any further comments in https://github.com/agamemnus/cordova-plugin-xapkreader/issues/22.

**Closed by agamemnus** 2015-06-06 21:05 UTC
